<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;

class ClubsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clubs')->delete();
        DB::table('clubs')->insert([
            [
                'name'             => 'Uruguay',
                'slug'             => 'uruguay',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 758,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
                'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Russia',
                'slug'             => 'russia',
                'club_category_id' => 1,
                'logo'             => 'http://fanslive-dev.s3.amazonaws.com/club/Flag_of_Russia.png',
                'logo_file_name'   => 'Flag_of_Russia.png',
                'status'           => 'Published',
                'external_app_id'  => 808,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Saudi Arabia',
                'slug'             => 'saudi-arabia',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 801,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Iran',
                'slug'             => 'iran',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 840,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Spain',
                'slug'             => 'spain',
                'club_category_id' => 1,
                'logo'             => 'http://fanslive-dev.s3.amazonaws.com/club/Flag_of_Spain.png',
                'logo_file_name'   => 'Flag_of_Spain.png',
                'status'           => 'Published',
                'external_app_id'  => 760,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Plymouth Argyle FC',
                'slug'             => 'plymouth-argyle-fc',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 1138,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Charlton Athletic FC',
                'slug'             => 'charlton-athletic-fc',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 348,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Luton Town FC',
                'slug'             => 'luton-town-fc',
                'club_category_id' => 1,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 389,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Scunthorpe United FC',
                'slug'             => 'scunthorpe-united-fc',
                'club_category_id' => 1,
                'logo'             => 'http://fanslive-dev.s3.amazonaws.com/club/Scunthorpe_United_FC_logo.png',
                'logo_file_name'   => 'Scunthorpe_United_FC_logo.png',
                'status'           => 'Published',
                'external_app_id'  => 1078,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Sunderland AFC',
                'slug'             => 'sunderland-afc',
                'club_category_id' => 1,
                'logo'             => 'http://fanslive-dev.s3.amazonaws.com/club/AFC_Sunderland.png',
                'logo_file_name'   => 'AFC_Sunderland.png',
                'status'           => 'Published',
                'external_app_id'  => 71,
                'primary_colour'   => '#11213C',
                'secondary_colour' => '#fbb819',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Real Madrid CF',
                'slug'             => 'real-madrid-cf',
                'club_category_id' => 4,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 86,
                'primary_colour'   => '#ffffff',
                'secondary_colour' => '#800080',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Juventus FC',
                'slug'             => 'juventus-fc',
                'club_category_id' => 4,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 109,
                'primary_colour'   => '#ffffff',
                'secondary_colour' => '#000000',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name'             => 'Manchester City FC',
                'slug'             => 'manchester-city-fc',
                'club_category_id' => 4,
                'logo'             => null,
                'logo_file_name'   => null,
                'status'           => 'Published',
                'external_app_id'  => 65,
                'primary_colour'   => '#87ceeb',
                'secondary_colour' => '#ffffff',
				'currency'		   => 'GBP',
                'created_at'       => Carbon::now()->format('Y-m-d H:i:s'),
            ]
        ]);
    }
}
